# シンプルな設定例
# 基本的な会話活性度予測用

data:
  columns:
    conversation_id: "cid"
    target: "class"
    exclude: []
  
  classes:
    numeric:
      mapping: {1: "LL", 2: "LM", 3: "MM", 4: "MH", 5: "HH"}
    string:
      mapping: {"LL": 1, "LM": 2, "MM": 3, "MH": 4, "HH": 5}
  
  validation:
    min_samples: 10
    min_features: 3
    max_missing_ratio: 0.5

preprocessing:
  missing_values:
    strategy: "mean"
    numeric_strategy: "mean"
    categorical_strategy: "mode"
  
  scaling:
    enabled: true
    method: "standard"
    by_conversation: false
  
  discretization:
    enabled: false
  
  feature_selection:
    enabled: true
    method: "percentile"
    percentile: 50
  
  temporal_features:
    enabled: false

split:
  test_size: 0.2
  random_state: 42
  by_conversation: false
  stratify: true

models:
  ensemble:
    enabled: true
    voting: "soft"
    classifiers: ["rf", "svm", "nb"]
  
  xgboost:
    enabled: false
  
  deep_learning:
    enabled: false

optimization:
  enabled: false

evaluation:
  metrics: ["accuracy", "precision", "recall", "f1"]
  cross_validation: true
  cv_folds: 5

output:
  models_dir: "./models"
  plots_dir: "./models"
  save_format: "pdf"
  save_plots: true
  save_models: true 